### ISSUE TITLE
the Programm dont starts!

### ISSUE THREAD

**Issue by stev96** [kripton/jukuzregie#1]
When i will be Start the Programm with the Terminalcommand "./jukuzregie". I becam an error:
"bash: ./jukuzregie: Ist ein Verzeichnis". Why they doesn´t starts?

**Comment by kripton** [comment]
Just what you shell tells you: it is a directory. Go into that directory using "cd jukuzregie" and try again.

Not a problem of my software though :/

**Comment by stev96** [comment]
So itś make nothing.... I became this message
"steven@steven:~/jukuzregie$ ./jukuzregie
bash: ./jukuzregie: Datei oder Verzeichnis nicht gefunden
steven@steven:~/jukuzregie$ "

**Comment by kripton** [comment]
Did you compile it? In that directory, run "qmake" and "make"
